# Generated by Django 5.1.3 on 2024-11-15 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo_app.shopping')),
            ],
        ),
    ]
